### ISSUE TITLE
Arguments for this implementation

### ISSUE THREAD

**Issue by 1kastner** [LLNL/SSHSpawner#1]
Hello there,

thank you very much for your shared project and the effort you put in it! Currently I am examining different implementations for a spawner over SSH. This was one of them. At the same time I found https://github.com/NERSC/sshspawner which has been around in the internet for a longer time. Did you know about that project before? Are there design decisions that are fundamentally different from theirs? What are the pros and cons? Thank you so much for the insights!

Best wishes
1kastner

**Comment by tgmachina** [comment]
Hello,

Yes, I am aware of NERSC's SSH spawner as well--the authors and I collaborate and meet from time to time.

In truth, my `spawner` would have been better named `SSHTunnelSpawner`. The main distinction between the two of our implementations is that I hold open the ssh connection and tunnel the port that gets assigned to the notebook. The advantage is that the target machine does not need to expose any additional high-numbered ports to make the notebook visible to the hub.

I'm actually moving away from the centralized hub model (i.e. not using `SSHSpawner`) in favor of hubs (or another solution) deployed locally on the target host. It's easier to point a reverse proxy to these individual hubs than it is to manage a single hub. There's a number of things that can go wrong spawning notebooks over SSH as different users in a heterogeneous environment.

In any event, hope that helps!

**Comment by 1kastner** [comment]
Thank you very much for your feedback! The first part seems clear to me but for the second part I would like to have some additional information. Is your description meant to display the difference between your spawner and the NERSC's sshspawner? In that case I have some difficulties to follow your remarks.

From my first impression I thought that both your "SSHTunnelSpawner" and NERSC's sshspawner connects to a remote machine and then just works with whatever is present on that machine. Therefore in both cases I can start to use Linux administration skills to configure different VMs and on a VM each users independently. Is that the heterogeneous environment that you mention?

**Comment by tgmachina** [comment]
For us, a heterogeneous environment means that we have different physical hosts with potentially different operating systems and user configurations. Spawning over SSH is more fragile in these conditions.

The second part isn't a comparison. It's to say I'd like to not use SSHSpawner anymore. For our use, it's easier to just start several different JupyterHub instances, one on each of the target hosts we'd ordinarily SSH to and let a reverse proxy route requests to the appropriate host. While it may or may not be an option for you, I just thought I would mention this as an alternative deployment route.

**Comment by 1kastner** [comment]
Thank you very much for your comments, things are much clearer to me now.
